module.exports = [
  ['https://apublica.org/feed/', 'Agencia Publica'],
  ['https://theintercept.com/brasil/feed/', 'Intercept Brasil'],
  ['https://ponte.org/feed/', 'Ponte Jornalismo'],
  ['https://observatoriodaimprensa.com.br/feed/', 'Observatorio da Imprensa'],
  ['https://outraspalavras.net/feed', 'Outras Palavras'],
  ['https://www.brasildefato.com.br/feed/', 'Brasil de Fato'],
  ['https://ojoioeotrigo.com.br/feed/', 'O Joio e o Trigo'],
  ['https://www.nucleo.jor.br/rss/', 'Nucleo Jornalismo'],
  ['https://agenciasportlight.com.br/index.php/feed/', 'Agencia Sportlight'],
  ['https://passapalavra.info/feed/', 'Passa Palavra'],
  ['https://www.nexojornal.com.br/rss.xml', 'Nexo Jornal'],
  ['https://vermelho.org.br/feed/', 'Vermelho'],
  ['https://jacobin.com.br/feed/', 'Jacobin Brasil'],
  ['https://mst.org.br/feed/', 'MST'],
  ['https://iclnoticias.com.br/feed/', 'ICL Noticias'],
  ['https://consultapopularoficial.org/feed/', 'Consulta Popular'],
  ['https://piaui.uol.com.br/feed/', 'Piaui'],
  ['https://noticiabrasil.net.br/export/rss2/archive/index.xml', 'Sputnik Brasil'],
  ['https://www.aljazeera.com/xml/rss/all.xml', 'Al Jazeera'],
  ['https://operamundi.uol.com.br/rss', 'Opera Mundi'],
  ['https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada', 'El Pais Mundo'],
  ['https://embaixadacuba.org.br/feed/', 'Embaixada de Cuba'],
  ['https://embaixadavenezuela.org.br/feed/', 'Embaixada da Venezuela'],
  ['https://embaixadabolivia.org.br/feed/', 'Embaixada da Bolivia'],
  ['https://embaixadanicaragua.org.br/feed/', 'Embaixada da Nicaragua'],
  ['https://embaixadaequador.org.br/feed/', 'Embaixada do Equador'],
  ['https://embaixadachile.org.br/feed/', 'Embaixada do Chile'],
  ['https://embaixadaargentina.org.br/feed/', 'Embaixada da Argentina'],
  ['https://embaixadamexico.org.br/feed/', 'Embaixada do Mexico'],
  ['https://embaixadauruguai.org.br/feed/', 'Embaixada do Uruguai'],
  ['https://embaixadaparaguai.org.br/feed/', 'Embaixada do Paraguai'],
  ['https://embaixadaperu.org.br/feed/', 'Embaixada do Peru'],
  ['https://revistaopera.com.br/feed/', 'Revista Opera'],
  ['https://subverta.com.br/feed/', 'Subverta'],
  ['https://ominhocario.com.br/feed/', 'O Minhocario'],
];
